image: snakepacker/python:all

test:
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    CI_MAPS_PG_URL: postgresql+asyncpg://user:hackme@localhost/maps
  script:
    - make devenv
    - make postgres
    - make pytest
