
services:
  - postgis/postgis
variables:
  POSTGRES_DB: maps
  POSTGRES_USER: user
  POSTGRES_PASSWORD: hackme
  POSTGRES_HOST_AUTH_METHOD: trust
  PGDATA: /var/lib/postgresql/data/pgdata

test:
  image: snakepacker/python:all
  script:
    - make devenv
    - make pytest
