test:
  before_script:
    - docker stop maps-postgres || true
    - docker run --rm --detach --name=maps-postgres --env POSTGRES_USER=user --env POSTGRES_PASSWORD=hackme --env POSTGRES_DB=maps --env PGDATA=/var/lib/postgresql/data/pgdata --volume /mnt:/var/lib/postgresql/data --publish 5432:5432 postgis/postgis
  image: snakepacker/python:all
  script:
    - make devenv
    - make pytest


