# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: snakepacker/python:all

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - env/

before_script:
  - make devenv
  - make postgres

test:
  script:
    - make pytest


