- name: create directory for maps app
  file:
    path: /etc/docker/compose/maps
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: deploy docker-compose.yml for maps app
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/maps/docker-compose.yml
    mode: 0640
    owner: root
    group: docker
  notify:
    - restart maps

- name: start & enable maps service
  service:
    name: docker-compose@maps
    # Сервис должен запускаться после перезагрузки
    enabled: yes
    # Сервис должен запуститься или быть уже запущен
    state: started

# Требуется для модуля docker_container
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements
- name: install python modules
  apt:
    name:
      - python3-docker
    update_cache: yes

# Требуется чтобы все обработчики (handlers) отработали немедленно,
# не дожидаясь обычных точек синхронизации
# https://docs.ansible.com/ansible/latest/modules/meta_module.html#parameters
- name: flush handlers
  meta: flush_handlers

- name: apply database migrations
  docker_container:
    name: db_migrator
    image: "{{ maps_image }}"
    command: ["maps-db", "upgrade", "head"]
    networks:
      - name: maps_default
    auto_remove: yes
    networks_cli_compatible: yes
    env:
      ANALYZER_PG_URL: postgresql://{{ maps_pg_user }}:{{ maps_pg_password }}@postgres/{{ maps_pg_dbname }}
