"""empty message

Revision ID: 5fc14689f6e5
Revises: 
Create Date: 2021-08-22 10:20:18.362977

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

from analyzer.api import DEFAULT_PLACES
from analyzer.db.schema import places_table as places_t

# revision identifiers, used by Alembic.
revision = '5fc14689f6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('place_uid', sa.String(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('place_title', sa.String(), nullable=True),
    sa.Column('coordinates', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=True),
    sa.PrimaryKeyConstraint('place_uid', name=op.f('pk__places'))
    )
    op.create_table('users',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_email', name=op.f('pk__users'))
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('place_uid', sa.String(), nullable=False),
    sa.Column('feedback_rate', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.CheckConstraint('feedback_rate >= 0 AND feedback_rate <= 5', name=op.f('ck__user_feedbacks__feedback_rate')),
    sa.ForeignKeyConstraint(['place_uid'], ['places.place_uid'], name=op.f('fk__user_feedbacks__place_uid__places')),
    sa.ForeignKeyConstraint(['user_email'], ['users.user_email'], name=op.f('fk__user_feedbacks__user_email__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_feedbacks')),
    sa.UniqueConstraint('user_email', 'place_uid')
    )
    op.create_table('user_places',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('place_uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['place_uid'], ['places.place_uid'], name=op.f('fk__user_places__place_uid__places')),
    sa.ForeignKeyConstraint(['user_email'], ['users.user_email'], name=op.f('fk__user_places__user_email__users')),
    sa.PrimaryKeyConstraint('user_email', 'place_uid', name=op.f('pk__user_places'))
    )
    op.bulk_insert(
        places_t,
        [
            {"place_uid": p_uid, "place_id": p_id,
             "place_title": f'DEFAULT_PLACE_{p_title}',
             "coordinates": 'POINT({} {})'.format(lon, lat)}
            for p_uid, p_id, lat, lon, p_title in DEFAULT_PLACES
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_places')
    op.drop_table('user_feedbacks')
    op.drop_table('users')
    op.drop_table('places')
    # ### end Alembic commands ###
